"""
CSM Head Circumference measurement - Agent-ready version (no interactive input)
Original: predict.py (kept as backup)
Usage: python predict_agent.py --data_path /path/to/images [--pixel_csv /path/to/pixel_size.csv]
"""
import argparse
import torch
import os
import cv2
import shutil
import numpy as np
import pandas as pd
from pathlib import Path
from modules import CSM, predict, mcc_edge, ellip_fit


_CKPT_ROOT = Path(os.environ.get("FETALAGENT_CKPT_DIR", str(Path(__file__).resolve().parents[3] / "FetalAgent_ckpt"))).resolve()


def load_pixel_sizes(csv_path):
    """Load pixel sizes from CSV file."""
    pixel_dict = {}
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        for _, row in df.iterrows():
            pixel_dict[row['filename']] = float(row['pixel size(mm)'])
    return pixel_dict


def main():
    parser = argparse.ArgumentParser(description='CSM Head Circumference Measurement (Agent-ready)')
    parser.add_argument('--data_path', type=str, required=True, help='Path to directory containing images')
    parser.add_argument('--pixel_csv', type=str, default=None,
                        help='Path to pixel_size.csv (default: <data_path>/pixel_size.csv)')
    parser.add_argument('--model_path', type=str,
                        default=str(_CKPT_ROOT / 'test_model.pth'),
                        help='Path to model checkpoint')
    parser.add_argument('--output_dir', type=str, default='../results_agent',
                        help='Output directory for predictions')
    args = parser.parse_args()

    # Setup output directories
    predict_folder = os.path.join(args.output_dir, 'predictions')
    edge_folder = os.path.join(args.output_dir, 'predictions_edge')
    
    if os.path.isdir(predict_folder):
        shutil.rmtree(predict_folder)
    os.makedirs(predict_folder)
    
    if os.path.isdir(edge_folder):
        shutil.rmtree(edge_folder)
    os.makedirs(edge_folder)

    # Load pixel sizes
    pixel_csv = args.pixel_csv if args.pixel_csv else os.path.join(args.data_path, "pixel_size.csv")
    pixel_sizes = load_pixel_sizes(pixel_csv)

    # Load the network
    net = CSM()
    net.load_state_dict(torch.load(args.model_path))

    # Run prediction
    # NOTE: modules.predict() concatenates output path via `predict_folder + filename`,
    # so predict_folder MUST end with a path separator.
    predict_folder_out = predict_folder if predict_folder.endswith(os.sep) else (predict_folder + os.sep)
    predict(net, args.data_path, predict_folder_out, device='cuda')

    # Process predictions
    dirs = os.listdir(predict_folder)
    results = []

    for img_name in dirs:
        if not img_name.endswith(".png"):
            continue

        img_path = os.path.join(predict_folder, img_name)
        img = cv2.imread(img_path, 0)
        if img is None:
            print(f"Warning: Could not read {img_path}")
            continue

        # Extract contour
        edge_img = mcc_edge(img)
        save_path = os.path.join(edge_folder, img_name)
        cv2.imwrite(save_path, edge_img)

        # Ellipse fitting
        xc, yc, theta, a, b = ellip_fit(edge_img)

        # Get original image dimensions
        orig_img_path = os.path.join(args.data_path, img_name)
        orig_img = cv2.imread(orig_img_path, 0)
        if orig_img is None:
            print(f"Warning: Original image not found: {orig_img_path}")
            continue

        gt_h, gt_w = orig_img.shape[:2]

        # Get pixel size from CSV or use default
        pixel_size = pixel_sizes.get(img_name, 0.15)

        # Prediction image size
        pred_h, pred_w = 32, 48

        # Scale factors
        scale_x = gt_w / pred_w
        scale_y = gt_h / pred_h

        # Scale ellipse parameters
        xc = (xc + 0.5) * scale_x - 0.5
        yc = (yc + 0.5) * scale_y - 0.5
        a = a * scale_x
        b = b * scale_y

        # Calculate HC using ellipse approximation formula
        hc = 2 * np.pi * b + 4 * (a - b)
        hc_mm = hc * pixel_size

        results.append({
            'filename': img_name,
            'hc_mm': hc_mm,
            'pixel_size': pixel_size
        })
        # Print per-image result immediately
        print(f"{img_name}: {hc_mm:.2f} mm", flush=True)

    if len(results) == 0:
        print("ERROR: no predictions were generated by CSM predict(); check input folder and output paths.", flush=True)
        raise SystemExit(2)


if __name__ == '__main__':
    main()

